In [1]:
import logging

import numpy as np
import pandas as pd

from blueetl.analysis import Analyzer
from blueetl.constants import *
from blueetl.utils import load_yaml

analysis_config_file = "../tests/data/tmp/analysis_config_01.yaml"
# analysis_config_file = "../tests/data/tmp/analysis_config_02.yaml"

In [2]:
loglevel = logging.WARNING
logformat = "%(asctime)s %(levelname)s %(name)s: %(message)s"
logging.basicConfig(format=logformat, level=loglevel)
np.random.seed(0)
analysis_config = load_yaml(analysis_config_file)
analysis_config

{'simulation_campaign': '/gpfs/bbp.cscs.ch/project/proj83/scratch/bbp_workflow/c26abad3-0861-4f7d-863c-a42daffd029f/config.json',
 'output': 'analysis_01_bnac',
 'extraction': {'neuron_classes': {'L1_EXC': {'layer': [1],
    'synapse_class': ['EXC']},
   'L23_EXC': {'layer': [2, 3], 'synapse_class': ['EXC']},
   'L4_EXC': {'layer': [4], 'synapse_class': ['EXC']},
   'L5_EXC': {'layer': [5], 'synapse_class': ['EXC']},
   'L6_EXC': {'layer': [6], 'synapse_class': ['EXC']},
   'L1_INH': {'layer': [1], 'synapse_class': ['INH']},
   'L23_INH': {'layer': [2, 3], 'synapse_class': ['INH']},
   'L4_INH': {'layer': [4], 'synapse_class': ['INH']},
   'L5_INH': {'layer': [5], 'synapse_class': ['INH']},
   'L6_INH': {'layer': [6], 'synapse_class': ['INH']}},
  'limit': None,
  'target': 'hex0',
  'windows': {'w1': {'bounds': [2000, 7000], 'window_type': 'spontaneous'},
   'w2': {'bounds': [0, 100],
    'initial_offset': 7000,
    'n_trials': 3,
    'trial_steps_value': 1000},
   'w3': {'bounds': [0, 25],
    'initial_offset': 7000,
    'n_trials': 5,
    'trial_steps_label': 'ts1'}},
  'trial_steps': {'ts1': {'function': 'blueetl.external.bnac.calculate_trial_step.onset_from_spikes',
    'initial_offset': 7000,
    'bounds': [-50, 25],
    'pre_window': [-50, 0],
    'post_window': [0, 25],
    'smoothing_width': 1.5,
    'histo_bins_per_ms': 5,
    'threshold_std_multiple': 4,
    'ms_post_offset': 1,
    'fig_paths': []}}},
 'analysis': {'features': [{'type': 'multi',
    'groupby': ['simulation_id', 'circuit_id', 'neuron_class', 'window'],
    'function': 'blueetl.external.bnac.calculate_features.calculate_features_multi',
    'params': {'export_all_neurons': True}}]}}

In [3]:
a = Analyzer(analysis_config, base_path='..', use_cache=True)

2022-04-08 10:47:43,461 WARNING blueetl.config.simulations: 'c26abad3-0861-4f7d-863c-a42daffd029f/000' is a directory, assuming BlueConfig as the config file
2022-04-08 10:47:43,462 WARNING blueetl.config.simulations: 'c26abad3-0861-4f7d-863c-a42daffd029f/001' is a directory, assuming BlueConfig as the config file
2022-04-08 10:47:43,463 WARNING blueetl.config.simulations: 'c26abad3-0861-4f7d-863c-a42daffd029f/002' is a directory, assuming BlueConfig as the config file
2022-04-08 10:47:43,464 WARNING blueetl.config.simulations: 'c26abad3-0861-4f7d-863c-a42daffd029f/003' is a directory, assuming BlueConfig as the config file

In [4]:
a.extract_repo()

In [5]:
a.calculate_features()

In [6]:
a.repo.names

['neuron_classes',
 'neurons',
 'simulations',
 'spikes',
 'trial_steps',
 'windows']

In [7]:
a.repo.simulations.df

                                         simulation_id  circuit_id  \
ca   shotn_mean_pct shotn_sd_pct seed
1.05 50             40           628462              0           0
     60             40           628462              1           0
1.15 50             40           628462              2           0
     60             40           628462              3           0

                                                                           simulation_path  \
ca   shotn_mean_pct shotn_sd_pct seed
1.05 50             40           628462  /gpfs/bbp.cscs.ch/project/proj83/scratch/bbp_w...
     60             40           628462  /gpfs/bbp.cscs.ch/project/proj83/scratch/bbp_w...
1.15 50             40           628462  /gpfs/bbp.cscs.ch/project/proj83/scratch/bbp_w...
     60             40           628462  /gpfs/bbp.cscs.ch/project/proj83/scratch/bbp_w...

                                                                                simulation  \
ca   shotn_mean_pct shotn_sd_pct seed
1.05 50             40           628462  <bluepy.simulation.Simulation object at 0x2aab...
     60             40           628462  <bluepy.simulation.Simulation object at 0x2aab...
1.15 50             40           628462  <bluepy.simulation.Simulation object at 0x2aab...
     60             40           628462  <bluepy.simulation.Simulation object at 0x2aab...

                                                                                   circuit
ca   shotn_mean_pct shotn_sd_pct seed
1.05 50             40           628462  <bluepy.circuit.Circuit object at 0x2aab7a229160>
     60             40           628462  <bluepy.circuit.Circuit object at 0x2aab7a229160>
1.15 50             40           628462  <bluepy.circuit.Circuit object at 0x2aab7a229160>
     60             40           628462  <bluepy.circuit.Circuit object at 0x2aab7a229160>

In [8]:
a.repo.neurons.df

       circuit_id neuron_class      gid  neuron_class_index
0               0       L1_INH      301                   0
1               0       L1_INH      335                   1
2               0       L1_INH      381                   2
3               0       L1_INH      555                   3
4               0       L1_INH      855                   4
...           ...          ...      ...                 ...
30185           0       L6_INH  2205763                 976
30186           0       L6_INH  2205788                 977
30187           0       L6_INH  2205940                 978
30188           0       L6_INH  2206090                 979
30189           0       L6_INH  2206091                 980

[30190 rows x 4 columns]

In [9]:
a.repo.neuron_classes.df

   circuit_id neuron_class  count limit target   layer synapse_class
0           0       L1_INH    291  None   hex0     [1]         [INH]
1           0      L23_EXC   7179  None   hex0  [2, 3]         [EXC]
2           0      L23_INH    994  None   hex0  [2, 3]         [INH]
3           0       L4_EXC   4568  None   hex0     [4]         [EXC]
4           0       L4_INH    302  None   hex0     [4]         [INH]
5           0       L5_EXC   4989  None   hex0     [5]         [EXC]
6           0       L5_INH    835  None   hex0     [5]         [INH]
7           0       L6_EXC  10051  None   hex0     [6]         [EXC]
8           0       L6_INH    981  None   hex0     [6]         [INH]

In [10]:
a.repo.trial_steps.df

,simulation_id,circuit_id,trial_steps_label,trial_steps_value,pre_mean,pre_std,post_max,pre_mean_post_max_ratio,cortical_onset
0,0,0,ts1,12.0,0.084,0.277388,17,0.004941,12.0
1,1,0,ts1,11.4,1.276,0.686894,28,0.045571,11.4
2,2,0,ts1,10.8,0.092,0.289026,23,0.004000,10.8
3,3,0,ts1,5.4,2.096,0.631493,46,0.045565,5.4

In [11]:
a.repo.windows.df

,simulation_id,circuit_id,window,trial,offset,t_start,t_stop,duration,window_type
0,0,0,w1,0,0.0,2000.0,7000.0,5000.0,spontaneous
1,0,0,w2,0,7000.0,0.0,100.0,100.0,
2,0,0,w2,1,8000.0,0.0,100.0,100.0,
3,0,0,w2,2,9000.0,0.0,100.0,100.0,
4,0,0,w3,0,7000.0,0.0,25.0,25.0,
5,0,0,w3,1,7012.0,0.0,25.0,25.0,
6,0,0,w3,2,7024.0,0.0,25.0,25.0,
7,0,0,w3,3,7036.0,0.0,25.0,25.0,
8,0,0,w3,4,7048.0,0.0,25.0,25.0,
9,1,0,w1,0,0.0,2000.0,7000.0,5000.0,spontaneous
10,1,0,w2,0,7000.0,0.0,100.0,100.0,
11,1,0,w2,1,8000.0,0.0,100.0,100.0,
12,1,0,w2,2,9000.0,0.0,100.0,100.0,
13,1,0,w3,0,7000.0,0.0,25.0,25.0,
14,1,0,w3,1,7011.4,0.0,25.0,25.0,
15,1,0,w3,2,7022.8,0.0,25.0,25.0,
16,1,0,w3,3,7034.2,0.0,25.0,25.0,
17,1,0,w3,4,7045.6,0.0,25.0,25.0,
18,2,0,w1,0,0.0,2000.0,7000.0,5000.0,spontaneous
19,2,0,w2,0,7000.0,0.0,100.0,100.0,
20,2,0,w2,1,8000.0,0.0,100.0,100.0,
21,2,0,w2,2,9000.0,0.0,100.0,100.0,
22,2,0,w3,0,7000.0,0.0,25.0,25.0,
23,2,0,w3,1,7010.8,0.0,25.0,25.0,
24,2,0,w3,2,7021.6,0.0,25.0,25.0,
25,2,0,w3,3,7032.4,0.0,25.0,25.0,
26,2,0,w3,4,7043.2,0.0,25.0,25.0,
27,3,0,w1,0,0.0,2000.0,7000.0,5000.0,spontaneous
28,3,0,w2,0,7000.0,0.0,100.0,100.0,
29,3,0,w2,1,8000.0,0.0,100.0,100.0,
30,3,0,w2,2,9000.0,0.0,100.0,100.0,
31,3,0,w3,0,7000.0,0.0,25.0,25.0,
32,3,0,w3,1,7005.4,0.0,25.0,25.0,
33,3,0,w3,2,7010.8,0.0,25.0,25.0,
34,3,0,w3,3,7016.2,0.0,25.0,25.0,
35,3,0,w3,4,7021.6,0.0,25.0,25.0,

In [12]:
a.repo.spikes.df

,time,gid,window,trial,simulation_id,circuit_id,neuron_class
0,2000.200,355828,w1,0,0,0,L23_EXC
1,2003.975,3241134,w1,0,0,0,L23_EXC
2,2010.875,644392,w1,0,0,0,L23_EXC
3,2019.400,3254415,w1,0,0,0,L23_EXC
4,2019.950,158267,w1,0,0,0,L23_EXC
...,...,...,...,...,...,...,...
186943,24.000,1389002,w3,4,3,0,L6_INH
186944,24.125,2180441,w3,4,3,0,L6_INH
186945,24.525,1397134,w3,4,3,0,L6_INH
186946,24.575,1724717,w3,4,3,0,L6_INH
186947,24.675,1371682,w3,4,3,0,L6_INH

In [13]:
a.features.names

['by_gid',
 'by_gid_and_trial',
 'by_neuron_class',
 'by_neuron_class_and_trial',
 'histograms']

In [14]:
a.features.by_gid.df

                                                                         first_spike_time_means_cort_zeroed  \
simulation_id circuit_id neuron_class window gid     neuron_class_index
0             0          L1_INH       w1     301     0                                                  NaN
                                             335     1                                                  NaN
                                             381     2                                                  NaN
                                             555     3                                                  NaN
                                             855     4                                                  NaN
...                                                                                                     ...
3             0          L6_INH       w3     2205763 976                                                NaN
                                             2205788 977                                                NaN
                                             2205940 978                                             22.200
                                             2206090 979                                             12.800
                                             2206091 980                                              8.725

                                                                         mean_spike_counts  \
simulation_id circuit_id neuron_class window gid     neuron_class_index
0             0          L1_INH       w1     301     0                                 0.0
                                             335     1                                 0.0
                                             381     2                                 0.0
                                             555     3                                 0.0
                                             855     4                                 0.0
...                                                                                    ...
3             0          L6_INH       w3     2205763 976                               0.0
                                             2205788 977                               0.0
                                             2205940 978                               0.2
                                             2206090 979                               1.0
                                             2206091 980                               0.6

                                                                         mean_firing_rates_per_second
simulation_id circuit_id neuron_class window gid     neuron_class_index
0             0          L1_INH       w1     301     0                                            0.0
                                             335     1                                            0.0
                                             381     2                                            0.0
                                             555     3                                            0.0
                                             855     4                                            0.0
...                                                                                               ...
3             0          L6_INH       w3     2205763 976                                          0.0
                                             2205788 977                                          0.0
                                             2205940 978                                          8.0
                                             2206090 979                                         40.0
                                             2206091 980                                         24.0

[362280 rows x 3 columns]

In [15]:
a.features.by_gid_and_trial.df

                                                                               count  \
simulation_id circuit_id neuron_class window trial gid     neuron_class_index
0             0          L1_INH       w1     0     301     0                       0
                                                   335     1                       0
                                                   381     2                       0
                                                   555     3                       0
                                                   855     4                       0
...                                                                              ...
3             0          L6_INH       w3     4     2205763 976                     0
                                                   2205788 977                     0
                                                   2205940 978                     1
                                                   2206090 979                     1
                                                   2206091 980                     0

                                                                               first
simulation_id circuit_id neuron_class window trial gid     neuron_class_index
0             0          L1_INH       w1     0     301     0                     NaN
                                                   335     1                     NaN
                                                   381     2                     NaN
                                                   555     3                     NaN
                                                   855     4                     NaN
...                                                                              ...
3             0          L6_INH       w3     4     2205763 976                   NaN
                                                   2205788 977                   NaN
                                                   2205940 978                  22.2
                                                   2206090 979                   2.0
                                                   2206091 980                   NaN

[1086840 rows x 2 columns]

In [16]:
a.features.by_neuron_class.df

                                              mean_of_mean_spike_counts  \
simulation_id circuit_id neuron_class window
0             0          L1_INH       w1                       0.000000
                                      w2                       0.000000
                                      w3                       0.000000
                         L23_EXC      w1                       0.200585
                                      w2                       0.013976
...                                                                 ...
3             0          L6_EXC       w2                       0.059397
                                      w3                       0.043100
                         L6_INH       w1                       6.031600
                                      w2                       0.192661
                                      w3                       0.154740

                                              mean_of_mean_firing_rates_per_second  \
simulation_id circuit_id neuron_class window
0             0          L1_INH       w1                                  0.000000
                                      w2                                  0.000000
                                      w3                                  0.000000
                         L23_EXC      w1                                  0.040117
                                      w2                                  0.139759
...                                                                            ...
3             0          L6_EXC       w2                                  0.593971
                                      w3                                  1.724008
                         L6_INH       w1                                  1.206320
                                      w2                                  1.926606
                                      w3                                  6.189602

                                              std_of_mean_firing_rates_per_second  \
simulation_id circuit_id neuron_class window
0             0          L1_INH       w1                                 0.000000
                                      w2                                 0.000000
                                      w3                                 0.000000
                         L23_EXC      w1                                 0.111197
                                      w2                                 0.668081
...                                                                           ...
3             0          L6_EXC       w2                                 1.473429
                                      w3                                 6.889945
                         L6_INH       w1                                 1.774459
                                      w2                                 2.850296
                                      w3                                12.744839

                                              mean_of_spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window
0             0          L1_INH       w1                                         0.000000
                                      w2                                         0.000000
                                      w3                                         0.000000
                         L23_EXC      w1                                         0.000040
                                      w2                                         0.000140
...                                                                                   ...
3             0          L6_EXC       w2                                         0.000594
                                      w3                                         0.001724
                         L6_INH       w1                                         0.001206
                                      w2                                         0.001927
                                      w3                                         0.006190

                                              min_of_spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window
0             0          L1_INH       w1                                        0.000000
                                      w2                                        0.000000
                                      w3                                        0.000000
                         L23_EXC      w1                                        0.000000
                                      w2                                        0.000000
...                                                                                  ...
3             0          L6_EXC       w2                                        0.000000
                                      w3                                        0.001154
                         L6_INH       w1                                        0.000000
                                      w2                                        0.000000
                                      w3                                        0.003874

                                              max_of_spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window
0             0          L1_INH       w1                                        0.000000
                                      w2                                        0.000000
                                      w3                                        0.000000
                         L23_EXC      w1                                        0.000418
                                      w2                                        0.001486
...                                                                                  ...
3             0          L6_EXC       w2                                        0.001293
                                      w3                                        0.002189
                         L6_INH       w1                                        0.006116
                                      w2                                        0.005097
                                      w3                                        0.010194

                                              argmax_spike_times_hist_1ms_bin
simulation_id circuit_id neuron_class window
0             0          L1_INH       w1                                    0
                                      w2                                    0
                                      w3                                    0
                         L23_EXC      w1                                  330
                                      w2                                   15
...                                                                       ...
3             0          L6_EXC       w2                                   12
                                      w3                                   12
                         L6_INH       w1                                  453
                                      w2                                   43
                                      w3                                   22

[108 rows x 7 columns]

In [17]:
a.features.by_neuron_class_and_trial.df

                                                    mean_of_spike_counts_for_each_trial
simulation_id circuit_id neuron_class window trial
0             0          L1_INH       w1     0                                 0.000000
                                      w2     0                                 0.000000
                                             1                                 0.000000
                                             2                                 0.000000
                                      w3     0                                 0.000000
...                                                                                 ...
3             0          L6_INH       w3     0                                 0.115189
                                             1                                 0.140673
                                             2                                 0.165138
                                             3                                 0.176351
                                             4                                 0.176351

[324 rows x 1 columns]

In [18]:
a.features.histograms.df

                                                  spike_times_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window bin
0             0          L1_INH       w1     0                               0.000000
                                             1                               0.000000
                                             2                               0.000000
                                             3                               0.000000
                                             4                               0.000000
...                                                                               ...
3             0          L6_INH       w3     20                              0.006320
                                             21                              0.006932
                                             22                              0.010194
                                             23                              0.006320
                                             24                              0.004893

                                                  spike_times_max_normalised_hist_1ms_bin  \
simulation_id circuit_id neuron_class window bin
0             0          L1_INH       w1     0                                       0.00
                                             1                                       0.00
                                             2                                       0.00
                                             3                                       0.00
                                             4                                       0.00
...                                                                                   ...
3             0          L6_INH       w3     20                                      0.62
                                             21                                      0.68
                                             22                                      1.00
                                             23                                      0.62
                                             24                                      0.48

                                                  smoothed_3ms_spike_times_max_normalised_hist_1ms_bin
simulation_id circuit_id neuron_class window bin
0             0          L1_INH       w1     0                                             0.000000
                                             1                                             0.000000
                                             2                                             0.000000
                                             3                                             0.000000
                                             4                                             0.000000
...                                                                                             ...
3             0          L6_INH       w3     20                                            0.999143
                                             21                                            0.996793
                                             22                                            0.993834
                                             23                                            0.991182
                                             24                                            0.989622

[184500 rows x 3 columns]