In [1]:
import logging

import numpy as np
import pandas as pd

from blueetl.analysis import Analyzer
from blueetl.constants import *
from blueetl.utils import load_yaml

# analysis_config_file = "../tests/data/tmp/analysis_config_01.yaml"
analysis_config_file = "../tests/data/tmp/analysis_config_02.yaml"

In [2]:
loglevel = logging.INFO
logformat = "%(asctime)s %(levelname)s %(name)s: %(message)s"
logging.basicConfig(format=logformat, level=loglevel)
np.random.seed(0)
analysis_config = load_yaml(analysis_config_file)
analysis_config

{'simulation_campaign': 'tests/data/tmp/simulation_campaign_02.yaml',
 'output': 'analysis_02_bluecv',
 'extraction': {'neuron_classes': {'L3_EXC': {'layer': [3],
    'synapse_class': ['EXC']},
   'L4_EXC': {'layer': [4], 'synapse_class': ['EXC']},
   'L3_INH': {'layer': [3], 'synapse_class': ['INH']},
   'L4_INH': {'layer': [4], 'synapse_class': ['INH']}},
  'limit': None,
  'target': 'hex0',
  'windows': {'w1': {'bounds': [3800, 4000]},
   'w2': {'bounds': [4800, 5000]},
   'w3': {'bounds': [5800, 6000]},
   'w4': {'bounds': [4000, 4200]},
   'w5': {'bounds': [5000, 5200]},
   'w6': {'bounds': [6000, 6200]}}},
 'analysis': {'features': [{'type': 'single',
    'name': 'by_gid',
    'groupby': ['simulation_id',
     'circuit_id',
     'neuron_class',
     'window',
     'gid'],
    'function': 'blueetl.external.bluecv.gid.calculate_features_by_gid',
    'params': {'MFR': {},
     'latency': {},
     'ISI': {},
     'CV': {},
     'spike_count': {}}},
   {'type': 'single',
    'name': 'by_neuron_class',
    'groupby': ['simulation_id', 'circuit_id', 'neuron_class', 'window'],
    'function': 'blueetl.external.bluecv.neuron_class.calculate_features_by_neuron_class',
    'params': {'PSTH': {'params': {'bin_size': 10}}, 'PSD': {}}},
   {'type': 'comparison',
    'function': 'blueetl.external.bluecv.comparison.calculate_comparison_features',
    'params': {'VR': {}, 'VP': {}}}]}}

In [3]:
a = Analyzer(analysis_config, base_path='..', use_cache=True)

2022-04-08 11:22:36,792 INFO blueetl.config.simulations: Detected internal config
2022-04-08 11:22:36,793 INFO blueetl.store.base: Using class ParquetStore with basedir /gpfs/bbp.cscs.ch/project/proj30/home/jupyter/blueetl/sources/blueetl/analysis_02_bluecv/repo
2022-04-08 11:22:36,794 INFO blueetl.store.base: Using class ParquetStore with basedir /gpfs/bbp.cscs.ch/project/proj30/home/jupyter/blueetl/sources/blueetl/analysis_02_bluecv/features

In [4]:
a.extract_repo()

2022-04-08 11:22:36,868 INFO blueetl.repository: simulations dataframe loaded from existing data
2022-04-08 11:22:36,873 WARNING bluepy_configfile.configfile: Have keys ({'Date'}) that are not defined for section: Run
2022-04-08 11:22:36,874 INFO blueetl.extract.simulations: Loading simulation_id=0, circuit_id=0, circuit_hash=b206e4d81b6d18d5999c6894a41f0ca1339dd5fbbb3608e6dede14d2184cefaa, simulation_path=/gpfs/bbp.cscs.ch/data/scratch/proj83/home/bolanos/shot_noise_nd/hex_O1_superscan/output/perlayer/lognormal/awakequiet/Ca1p1/mean40/stdev30/rateVPM0p0/ratePOM0p0/fibersVPM0p1/fibersPOM0p0/latencyVPM1p63_0p22/latencyPOM2p98_0p32/inputRep5/inputRepDelay1000/seed294851/BlueConfig
2022-04-08 11:22:36,889 INFO blueetl.repository: neurons dataframe loaded from existing data
2022-04-08 11:22:36,899 INFO blueetl.repository: neuron_classes dataframe loaded from existing data
2022-04-08 11:22:36,904 INFO blueetl.repository: trial_steps dataframe loaded from existing data
2022-04-08 11:22:36,910 INFO blueetl.repository: windows dataframe loaded from existing data
2022-04-08 11:22:36,927 INFO blueetl.repository: spikes dataframe loaded from existing data

In [5]:
a.calculate_features()

2022-04-08 11:22:36,934 INFO blueetl.features: Calculating features 1/3 [type: single]
2022-04-08 11:23:59,642 INFO blueetl.features: Completed calculate_features_single [82.71 seconds]
2022-04-08 11:23:59,671 INFO blueetl.features: Calculating features 2/3 [type: single]
2022-04-08 11:24:15,333 INFO blueetl.features: Completed calculate_features_single [15.66 seconds]
2022-04-08 11:24:15,340 INFO blueetl.features: Calculating features 3/3 [type: comparison]
2022-04-08 11:24:15,341 WARNING blueetl.features: Comparison features not implemented

In [6]:
a.repo.names

['neuron_classes',
 'neurons',
 'simulations',
 'spikes',
 'trial_steps',
 'windows']

In [7]:
a.repo.simulations.df

,simulation_id,circuit_id,simulation_path,simulation,circuit
seed,,,,,
294851,0,0,/gpfs/bbp.cscs.ch/data/scratch/proj83/home/bol...,<bluepy.simulation.Simulation object at 0x2aab...,<bluepy.circuit.Circuit object at 0x2aab27a300a0>

In [8]:
a.repo.neurons.df

      circuit_id neuron_class      gid  neuron_class_index
0              0       L3_EXC     8750                   0
1              0       L3_EXC     8844                   1
2              0       L3_EXC     8942                   2
3              0       L3_EXC     9405                   3
4              0       L3_EXC     9549                   4
...          ...          ...      ...                 ...
9344           0       L4_INH  2884928                 297
9345           0       L4_INH  2884986                 298
9346           0       L4_INH  2885155                 299
9347           0       L4_INH  2885280                 300
9348           0       L4_INH  2885467                 301

[9349 rows x 4 columns]

In [9]:
a.repo.neuron_classes.df

   circuit_id neuron_class  count limit target layer synapse_class
0           0       L3_EXC   4078  None   hex0   [3]         [EXC]
1           0       L3_INH    401  None   hex0   [3]         [INH]
2           0       L4_EXC   4568  None   hex0   [4]         [EXC]
3           0       L4_INH    302  None   hex0   [4]         [INH]

In [10]:
a.repo.trial_steps.df

Empty DataFrame
Columns: [simulation_id, circuit_id, trial_steps_label, trial_steps_value]
Index: []

In [11]:
a.repo.windows.df

,simulation_id,circuit_id,window,trial,offset,t_start,t_stop,duration,window_type
0,0,0,w1,0,0,3800.0,4000.0,200.0,
1,0,0,w2,0,0,4800.0,5000.0,200.0,
2,0,0,w3,0,0,5800.0,6000.0,200.0,
3,0,0,w4,0,0,4000.0,4200.0,200.0,
4,0,0,w5,0,0,5000.0,5200.0,200.0,
5,0,0,w6,0,0,6000.0,6200.0,200.0,

In [12]:
a.repo.spikes.df

           time      gid window  trial  simulation_id  circuit_id neuron_class
0      3809.175    57119     w1      0              0           0       L3_EXC
1      3809.325   583707     w1      0              0           0       L3_EXC
2      3809.375   461452     w1      0              0           0       L3_EXC
3      3810.425    48942     w1      0              0           0       L3_EXC
4      3810.425   205703     w1      0              0           0       L3_EXC
...         ...      ...    ...    ...            ...         ...          ...
60255  6190.750  2796595     w6      0              0           0       L4_INH
60256  6194.250  2884778     w6      0              0           0       L4_INH
60257  6194.500  2877734     w6      0              0           0       L4_INH
60258  6194.850  2882619     w6      0              0           0       L4_INH
60259  6199.100  2874116     w6      0              0           0       L4_INH

[60260 rows x 7 columns]

In [13]:
a.features.names

['by_gid', 'by_neuron_class']

In [14]:
a.features.by_gid.df

                                                        MFR  latency     ISI  \
simulation_id circuit_id neuron_class window gid
0             0          L3_EXC       w1     8750     0.000      NaN     NaN
                                             8844     0.000      NaN     NaN
                                             8942     0.000      NaN     NaN
                                             9405     0.000      NaN     NaN
                                             9549     0.000      NaN     NaN
...                                                     ...      ...     ...
                         L4_INH       w6     2884928  0.030   13.775   7.350
                                             2884986  0.010   16.775  67.475
                                             2885155  0.025   13.825  23.775
                                             2885280  0.005   12.825     NaN
                                             2885467  0.005   23.750     NaN

                                                            CV  spike_count
simulation_id circuit_id neuron_class window gid
0             0          L3_EXC       w1     8750          NaN            1
                                             8844          NaN            1
                                             8942          NaN            1
                                             9405          NaN            1
                                             9549          NaN            1
...                                                        ...          ...
                         L4_INH       w6     2884928  0.414176            6
                                             2884986  0.000000            2
                                             2885155  0.349453            5
                                             2885280       NaN            1
                                             2885467       NaN            1

[56094 rows x 5 columns]

In [15]:
a.features.by_gid_and_trial.df

AttributeError: 'FeaturesCollection' object has no attribute 'by_gid_and_trial'

In [ ]:
a.features.by_neuron_class.df

In [ ]:
a.features.by_neuron_class_and_trial.df

In [ ]:
a.features.histograms.df